[package]
name = "minimap-binseq"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "mmr"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
minimap2 = { version = "0.1.23", default-features = false, features = [
    "simde",
] }
binseq = { git = "ssh://github.com/noamteyssier/binseq" }
serde = { version = "1.0.217", features = ["derive", "rc"] }
csv = "1.3.1"
parking_lot = "0.12.3"
clap = { version = "4.5.26", features = ["derive"] }
paraseq = "0.1.2"
niffler = "3.0.0"
num_cpus = "1.16.0"
indicatif = "0.17.11"
serde_json = "1.0.138"

[profile.release]
lto = true
codegen-units = 1
