[package]
name = "minimap-binseq"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
minimap2 = { version = "0.1.23", default-features = false, features = [
    "simde",
] }
binseq = { git = "ssh://github.com/noamteyssier/binseq" }
serde = { version = "1.0.217", features = ["derive", "rc"] }
csv = "1.3.1"
parking_lot = "0.12.3"
clap = { version = "4.5.26", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
